version: "3.9"

services:
  users_db:
    container_name: drs_users_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: quiz_users_db
    ports:
      - "3307:3306"
    volumes:
      - users_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p1234"]
      interval: 3s
      timeout: 2s
      retries: 30

  quiz_db:
    container_name: drs_quiz_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: quiz_db
    ports:
      - "3308:3306"
    volumes:
      - quiz_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p1234"]
      interval: 3s
      timeout: 2s
      retries: 30

  quizservice:
    container_name: drs-flask-quizService
    build:
      context: ./quizService
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8001"
    volumes:
      - ./quizService:/app
    environment:
      FLASK_ENV: development
      PORT: 8001
      SERVER_URL: "http://server:8000"
      DATABASE_URL: "mysql+pymysql://root:1234@quiz_db:3306/quiz_db"
    depends_on:
      quiz_db:
        condition: service_healthy

  server:
    container_name: drs-flask-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      FLASK_ENV: development
      PORT: 8000
      QUIZ_SERVICE_BASE_URL: "http://quizservice:8001"
      DATABASE_URL: "mysql+pymysql://root:1234@users_db:3306/quiz_users_db"
    depends_on:
      users_db:
        condition: service_healthy
      quizservice:
        condition: service_started

  client:
    container_name: drs-react-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      VITE_API_URL: "http://localhost:8000"
    depends_on:
      - server
      - quizservice

volumes:
  users_db_data:
  quiz_db_data:
