services:
  users_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: quiz_users_db
    ports:
      - "3307:3306"
    volumes:
      - users_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p1234"]
      interval: 3s
      timeout: 2s
      retries: 30

  quiz_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: quiz_db
    ports:
      - "3308:3306"
    volumes:
      - quiz_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p1234"]
      interval: 3s
      timeout: 2s
      retries: 30

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      QUIZ_SERVICE_BASE_URL: "http://quizservice:8001"
      DATABASE_URL: "mysql+pymysql://root:1234@users_db:3306/quiz_users_db"
    depends_on:
      users_db:
        condition: service_healthy

  quizservice:
    build:
      context: ./quizService
      dockerfile: Dockerfile.prod
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      SERVER_URL: "http://server:8000"
      DATABASE_URL: "mysql+pymysql://root:1234@quiz_db:3306/quiz_db"
    depends_on:
      quiz_db:
        condition: service_healthy

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "5173:80"
    depends_on:
      - server
      - quizservice

volumes:
  users_db_data:
  quiz_db_data:
