services:
  backend:
    container_name: drs-flask-backend
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      FLASK_ENV: development
      DB_HOST: users_db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: quiz_users_db
    depends_on:
      - users_db

  quizservice:
    container_name: drs-quizService
    build: ./quizService
    ports:
      - "5001:5001"
    volumes:
      - ./quizService:/app
    environment:
      FLASK_ENV: development
      DB_HOST: quiz_db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: quiz_db
    depends_on:
      - quiz_db

  users_db:
    container_name: drs_users_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: quiz_users_db
    ports:
      - "3307:3306"
    volumes:
      - users_db_data:/var/lib/mysql

  quiz_db:
    container_name: drs_quiz_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: quiz_db
    ports:
      - "3308:3306"
    volumes:
      - quiz_db_data:/var/lib/mysql

  frontend:
    container_name: drs-react-frontend
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
      - quizservice

volumes:
  users_db_data:
  quiz_db_data:
